spring.application.name=my-cloud

spring.datasource.url=jdbc:postgresql://localhost:5432/my_cloud_db
spring.datasource.username=andre
spring.datasource.password=andre

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret = "my-super-secret-key-nobody-his-aknowledge-4321"
jwt.expiration = 86400000